/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pdale' at '8/6/15 1:20 PM' with Gradle 2.5
 *
 * @author pdale, @date 8/6/15 1:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
