import org.junit.Test;

import java.io.PrintStream;

import static org.junit.Assert.*;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'pdale' at '8/6/15 1:20 PM' with Gradle 2.5
 *
 * @author pdale, @date 8/6/15 1:20 PM
 */
public class ApplicationXTest {
    @Test public void shouldDrawBoardWhenApplicationStarts() {
        PrintStream printStream = mock(PrintStream.class);

        ApplicationX application = new ApplicationX(printStream);
        application.run();

        verify(printStream).print("  |  |\n---------\n  |  |\n" +
                "---------\n  |  |");
    }
}
