import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.when;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'pdale' at '8/6/15 1:20 PM' with Gradle 2.5
 *
 * @author pdale, @date 8/6/15 1:20 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        when()
    }
}
