import org.junit.Before;
import org.junit.Test;

import java.io.PrintStream;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'pdale' at '8/6/15 1:20 PM' with Gradle 2.5
 *
 * @author pdale, @date 8/6/15 1:20 PM
 */
public class TicTacToeTest {
    TicTacToe application;
    PrintStream printStream;
    Player player;

    @Before
    public void setUp() throws Exception {
        printStream = mock(PrintStream.class);
        player = mock(Player.class);
        application = new TicTacToe(printStream, player);
    }

    @Test public void shouldDrawBoardWhenApplicationStarts() {
        application.run();

        verify(printStream).println(" | | \n------\n | | \n" +
                "------\n | | ");
    }

    @Test
    public void shouldDetermineNextMoveLocationFromPlayerWhenApplicationStarts() throws Exception {
        application.run();

        verify(player).nextMoveLocation();
    }

    @Test
    public void shouldPromptPlayerToEnterALocationToMoveWhenAplicationStarts() throws Exception {
        application.run();

        verify(printStream).print("Enter a number between 1 and 9: ");
    }

    @Test
    public void shouldDrawXInSquareOneOfBoardWhenPlayerInputs1() throws Exception {
        when(player.nextMoveLocation()).thenReturn("1");
        application.run();

        verify(printStream).println("X| | \n------\n | | \n" +
                "------\n | | ");
    }
}
