import org.junit.Before;
import org.junit.Test;

import java.io.PrintStream;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'pdale' at '8/6/15 1:20 PM' with Gradle 2.5
 *
 * @author pdale, @date 8/6/15 1:20 PM
 */
public class TicTacToeTest {
    TicTacToe application;
    PrintStream printStream;
    Player player;

    @Before
    public void setUp() throws Exception {
        printStream = mock(PrintStream.class);
        player = mock(Player.class);
        application = new TicTacToe(printStream, player);
    }

    @Test public void shouldDrawBoardWhenApplicationStarts() {
        application.run();

        verify(printStream).print(" | |\n------\n | |\n" +
                "------\n | |\n");
    }

    @Test
    public void shouldDetermineNextMoveLocationFromPlayerWhenApplicationStarts() throws Exception {
        application.run();

        verify(player).nextMoveLocation();
    }
}
